In [1]:
import pandas as pd                                    # for reading csv file
import matplotlib.pyplot as plt                        # for data visualization
from sklearn import tree                            
import numpy as np                                     # for linear algebra

In [2]:
cars_data = pd.read_csv("Data/cars.csv",  header=None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [3]:
cars_data.shape

(1728, 7)

In [4]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [5]:
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [6]:
for col in cars_data.columns:
    print("----------------{}------------------".format(col))
    print(cars_data[col].value_counts())
    print()

----------------buying------------------
low      432
med      432
high     432
vhigh    432
Name: buying, dtype: int64

----------------maint------------------
low      432
med      432
high     432
vhigh    432
Name: maint, dtype: int64

----------------doors------------------
4        432
3        432
5more    432
2        432
Name: doors, dtype: int64

----------------persons------------------
4       576
2       576
more    576
Name: persons, dtype: int64

----------------lug_boot------------------
small    576
med      576
big      576
Name: lug_boot, dtype: int64

----------------safety------------------
med     576
high    576
low     576
Name: safety, dtype: int64

----------------classes------------------
unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64



In [7]:
cars_data["classes"].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [8]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [9]:
cars_df=pd.DataFrame.copy(cars_data)

In [10]:
colname=cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [11]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   classes   1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [12]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x])
    le_name= dict(zip(le.classes_, le.transform(le.classes_)))
    print("Feature: ",x)
    print("Mapping: ", le_name)

Feature:  buying
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature:  maint
Mapping:  {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature:  doors
Mapping:  {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature:  persons
Mapping:  {'2': 0, '4': 1, 'more': 2}
Feature:  lug_boot
Mapping:  {'big': 0, 'med': 1, 'small': 2}
Feature:  safety
Mapping:  {'high': 0, 'low': 1, 'med': 2}
Feature:  classes
Mapping:  {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [13]:
cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [14]:
X=cars_df.values[:, :-1]
y=cars_df.values[:,  -1]

In [15]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.3,
                                                    random_state=10)

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)
print(X_train_scale.shape, y_train.shape)
print(X_test_scale.shape, y_test.shape)

(1209, 6) (1209,)
(519, 6) (519,)


In [17]:
from sklearn import tree 

In [18]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(criterion='gini',random_state=10, min_samples_leaf=5, min_samples_split=20, max_leaf_nodes=15, max_depth=6)

model_dt.fit(X_train_scale, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=15,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=20,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=10, splitter='best')

In [19]:
model_dt.get_depth()

6

In [20]:
y_pred= model_dt.predict(X_test_scale)

print(list(zip(y_test, y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 0), (2, 2), (2, 0), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 0), (0, 0), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (1, 0), (3, 3), (1, 0), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0),

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

print(accuracy_score(y_test, y_pred))

[[ 81   0  13   8]
 [ 17   0   0   4]
 [ 19   0 352   0]
 [  0   0   0  25]]
              precision    recall  f1-score   support

           0       0.69      0.79      0.74       102
           1       0.00      0.00      0.00        21
           2       0.96      0.95      0.96       371
           3       0.68      1.00      0.81        25

    accuracy                           0.88       519
   macro avg       0.58      0.69      0.63       519
weighted avg       0.86      0.88      0.87       519

0.882466281310212


C:\Users\91989\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
# %%time

# fig= plt.figure(figsize=(500,400))
# dot_data = tree.plot_tree(model_dt,
#                          feature_names=cars_df.columns[:-1],
#                          class_names=cars_df.columns[-1],
#                          filled=True)
# plt.savefig("test_mode.jpeg")

## Bagging approach 

### BaggingClassifier

In [23]:
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier

model= BaggingClassifier(n_estimators=100, random_state=10)

model = model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

print(accuracy_score(y_test, y_pred))

[[102   0   0   0]
 [  1  20   0   0]
 [  2   0 369   0]
 [  1   0   0  24]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       102
           1       1.00      0.95      0.98        21
           2       1.00      0.99      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.98      0.98       519
weighted avg       0.99      0.99      0.99       519

0.9922928709055877


### ExtraTreesClassifier

In [25]:
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier

model= ExtraTreesClassifier(n_estimators=100, random_state=10)

model = model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

print(accuracy_score(y_test, y_pred))

[[101   1   0   0]
 [  3  18   0   0]
 [  1   0 370   0]
 [  1   2   0  22]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       102
           1       0.86      0.86      0.86        21
           2       1.00      1.00      1.00       371
           3       1.00      0.88      0.94        25

    accuracy                           0.98       519
   macro avg       0.95      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519

0.9845857418111753


### RandomForestClassifier

In [27]:
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier

model= RandomForestClassifier(n_estimators=100, random_state=10)

model = model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

print(accuracy_score(y_test, y_pred))

[[ 99   3   0   0]
 [  3  18   0   0]
 [  2   0 369   0]
 [  2   0   0  23]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       102
           1       0.86      0.86      0.86        21
           2       1.00      0.99      1.00       371
           3       1.00      0.92      0.96        25

    accuracy                           0.98       519
   macro avg       0.95      0.94      0.94       519
weighted avg       0.98      0.98      0.98       519

0.9807321772639692
